const DonationsData = {
    cardDonations: [
        {
            id: 1,
            fecha: "11/04/2022",
            donante: "Donante 1",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
        {
            id: 2,
            fecha: "11/04/2022",
            donante: "Donante 2",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
        {
            id: 3,
            fecha: "11/04/2022",
            donante: "Donante 3",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
        {
            id: 4,
            fecha: "11/04/2022",
            donante: "Donante 4",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
        {
            id: 5,
            fecha: "11/04/2022",
            donante: "Donante 5",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
        {
            id: 6,
            fecha: "11/04/2022",
            donante: "Donante 6",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
        {
            id: 7,
            fecha: "11/04/2022",
            donante: "Donante 7",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
        {
            id: 8,
            fecha: "11/04/2022",
            donante: "Donante 8",
            direccion: "Un Lugar en ESA",
            tipo: "Materiales",
            concepto: "Cuatrocientos 0/100",
            total: 400,
        },
    ],
};

export default DonationsData;