const InventoryData = {
    cardInventory: [
        {
            id: 1,
            familiaId: 1,
            nombre: "Inventario 1",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
        {
            id: 2,
            familiaId: 2,
            nombre: "Inventario 2",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
        {
            id: 3,
            familiaId: 3,
            nombre: "Inventario 3",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
        {
            id: 4,
            familiaId: 4,
            nombre: "Inventario 4",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
        {
            id: 5,
            familiaId: 5,
            nombre: "Inventario 5",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
        {
            id: 6,
            familiaId: 6,
            nombre: "Inventario 6",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
        {
            id: 7,
            familiaId: 7,
            nombre: "Inventario 7",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
        {
            id: 8,
            familiaId: 8,
            nombre: "Inventario 8",
            unidad: 2,
            existencia: 3,
            cantidad: 4,
            costo: 3.25,
            precio: 6.5,
        },
    ],
};

export default InventoryData;