const SalesData = {
    cardSales: [
        {
            id: 1,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        {
            id: 2,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        {
            id: 3,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        {
            id: 4,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        {
            id: 5,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        {
            id: 6,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        {
            id: 7,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        {
            id: 8,
            cliente: "Nombre Apellido",
            direccion: "Un lugar en ESA",
            fecha: "11/04/2022",
            cuenta: 3,
            dui: "00000000-0",
            cantidad: 3,
            descripcion: "Venta de Sogas",
            total: 12.5,
        },
        
    ],
};

export default SalesData;